l = [1,7,3,4,'Akash',6.3,int(input())]
print(l)
print(l[0])
print(l[1])
print(l[2])
print(l[3])
print(l[-1])
print(l[-2])
print(l[-3])
print(l[-4])
print('the type of l is:',type(l))
print(type(l[4]))
print(type(l[3]))
print(type(l[5]))
print(type(l[6]))