print("Whats your Name?")
n = str(input())
print("Hello",n,"I think you're doing good")
print("Can I know where are you from?")
m=str(input())
print("Oh! Thats a great place, How is the whether there?")
q=str(input())
print("ok..., Whats your age?")
s=int(input())
print("Ooh that's great","you're",s,"years old that's good")